import * as fs from 'fs';
import * as path from 'path';
import  yaml  from 'yaml'; // 💡 استيراد مكتبة الـ YAML الجديدة

interface SwaggerOptions {
  title?: string | undefined;
  version?: string | undefined;
  desc?: string | undefined;
}

export function writeSwaggerFile(outputPath: string, pathsData: Record<string, any>, options: SwaggerOptions): void {
  
  // إعداد القيم الافتراضية الذكية للمشروع
  let localTitle = "DocuMind Generated API";
  let localVersion = "1.0.0";
  let localDesc = "Automated OpenAPI documentation generated by DocuMind AI.";

  try {
    const localPackageJsonPath = path.resolve('./package.json');
    if (fs.existsSync(localPackageJsonPath)) {
      const pkg = JSON.parse(fs.readFileSync(localPackageJsonPath, 'utf8'));
      if (pkg.name) localTitle = `${pkg.name} API Documentation`;
      if (pkg.version) localVersion = pkg.version;
      if (pkg.description) localDesc = pkg.description;
    }
  } catch (e) {}

  const swaggerDoc = {
    openapi: "3.0.0",
    info: {
      title: options.title || localTitle,
      version: options.version || localVersion,
      description: options.desc || localDesc,
    },
    ...pathsData,
  };

  const fullPath = path.resolve(outputPath);
  const fileExtension = path.extname(fullPath).toLowerCase();

  let fileContent: string;

  // 💡 الفحص الذكي: لو الملف ينتهي بـ yaml أو yml، حوله لـ YAML
  if (fileExtension === '.yaml' || fileExtension === '.yml') {
    fileContent = yaml.stringify(swaggerDoc);
  } else {
    // لو المستخدم كتب مسار ينتهي بـ .json صراحة، هيطلعه JSON منظم
    fileContent = JSON.stringify(swaggerDoc, null, 2);
  }

  fs.writeFileSync(fullPath, fileContent, 'utf8');
  console.log(`\n🎉 Success! Swagger documentation saved to: ${fullPath}`);
}