import * as fs from 'fs';
import * as path from 'path';
import yaml from 'yaml';

interface SwaggerOptions {
  title?: string | undefined;
  version?: string | undefined;
  desc?: string | undefined;
}

/**
 * Writes an OpenAPI document as YAML or JSON to disk.
 * @param outputPath Destination file path.
 * @param pathsData Merged OpenAPI paths and components.
 * @param options Title, version, and description metadata.
 */
export function writeSwaggerFile(outputPath: string, pathsData: Record<string, any>, options: SwaggerOptions): void {
    let localTitle = 'DocuMind Generated API';
    let localVersion = '1.0.0';
    let localDesc = 'Automated OpenAPI documentation generated by DocuMind AI.';

    try {
        const localPackageJsonPath = path.resolve('./package.json');
        if (fs.existsSync(localPackageJsonPath)) {
            const pkg = JSON.parse(fs.readFileSync(localPackageJsonPath, 'utf8'));
            if (pkg.name) localTitle = `${pkg.name} API Documentation`;
            if (pkg.version) localVersion = pkg.version;
            if (pkg.description) localDesc = pkg.description;
        }
    } catch (e) {}

    const swaggerDoc = {
        openapi: '3.0.0',
        info: {
            title: options.title || localTitle,
            version: options.version || localVersion,
            description: options.desc || localDesc
        },
        ...pathsData
    };

    const fullPath = path.resolve(outputPath);
    const fileExtension = path.extname(fullPath).toLowerCase();

    let fileContent: string;

    if (fileExtension === '.yaml' || fileExtension === '.yml') {
        fileContent = yaml.stringify(swaggerDoc);
    } else {
        fileContent = JSON.stringify(swaggerDoc, null, 2);
    }

    fs.writeFileSync(fullPath, fileContent, 'utf8');
    console.log(`\n🎉 Success! Swagger documentation saved to: ${fullPath}`);
}